version: '3.8'

services:
  web:
    build:
      context: ../../
      dockerfile: Dockerfile
    container_name: abyss_prod_app
    restart: unless-stopped
    ports:
      - "8080:8000"
    networks:
      - abyss-nw
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:dbpassword@db:5432/abyss-db
      - DJANGO_SETTINGS_MODULE=abyss.settings.prod
      - ALLOW_HOST=abyss.hanz.lol
      - RESEND_API_KEY=${RESEND_API_KEY}

  db:
    image: postgres:15-bookworm
    container_name: abyss_prod_postgres_db
    restart: unless-stopped
    networks:
      - abyss-nw
      - db
    volumes:
      - /opt/databases/prod/abyss/postgresql/db:/var/lib/postgresql/db
    environment:
      - POSTGRES_DB=abyss-db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=dbpassword
      - PGDATA=/var/lib/postgresql/db
      # Add other PostgreSQL configurations as needed

networks:
  abyss-nw:
    driver: bridge
  db:

